### ISSUE TITLE
Points to discuss 8.03 meeting

### ISSUE THREAD

**Issue by franadr** [franadr/UL-IL-2017-g07#7]
Write here question for 8.03 project meeting

**Comment by franadr** [comment]
- Link and differences between Alert and Crisis ?

- relation : ctAlert <-> ctCrisis not represented in the implementation ? (p 62)

- Crisis not deleted if Alert is invalidate ?

- Coordinator can not connect directly at a fresh start ?

**Comment by zkmok** [comment]
- Different Interfaces/Procedures using oeLogin for Admin/Coordinator
